# Generated by Django 4.0.4 on 2023-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_session_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_notification',
            name='status',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
