# Generated by Django 4.0.4 on 2023-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_employee_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
